### ISSUE TITLE
还是不行 

### ISSUE THREAD

**Issue by guangre** [Guyutongxue/VSCodeConfigHelper3#11]
D:/BaiduNetdiskDownload/x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file d:\clanguage\helloworld.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
终端进程“D:\BaiduNetdiskDownload\x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0\mingw64\bin\g++.exe '-std=c++17', '-Wall', '-Wextra', '-fexec-charset=GBK', '-g', 'd:\clanguage\helloworld.cpp', '-o', 'd:\clanguage\helloworld.exe'”已终止，退出代码: 1。

**Comment by guyutongxue** [comment]
helloworld.exe 程序已在运行，此时不能重新编译。请关闭所有正在运行的程序窗口、内置终端等，然后再试。

**Comment by guyutongxue** [comment]
Close due to inactivity.
