### ISSUE TITLE
配置时出现错误："Internal error: [json.exception.type_error.302] type must be string, but is null"

### ISSUE THREAD

**Issue by IsaacTheMouse** [Guyutongxue/VSCodeConfigHelper3#12]
VSCodeConfigHelper_v3.1.4_win
web页面提示：配置时出现错误："Internal error: [json.exception.type_error.302] type must be string, but is null"
![image](https://user-images.githubusercontent.com/49868138/149676871-1ef65050-7618-45c7-b35a-73b11bc7be5c.png)

**Comment by guyutongxue** [comment]
请将工具生成的 `vscch.log` 附上，以便我查看问题所在，谢谢

**Comment by IsaacTheMouse** [comment]
[vscch.log](https://paste.ubuntu.com/p/wJSrzn6zms/)

**Comment by guyutongxue** [comment]
您现在只需删除工具同路径下的 `profile.json`，然后重新配置（但尽量不要更改最后一步的各种编译选项）。

这是一个 bug，稍后我将修复它。
