### ISSUE TITLE
程序运行报错“缺少libstdc++-6.dll”

### ISSUE THREAD

**Issue by KingRayCao** [Guyutongxue/VSCodeConfigHelper3#20]
按照软件配置后，按F5运行报错：
Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc000007b.
直接运行exe，显示缺少libstdc++-6.dll
经排查，将mingw的bin文件夹中的libstdc++-6.dll复制到工作目录方能解决，不知是何原因？
OS: Windows11 21H2 22000.832.0，已安装Visual Studio

**Comment by guyutongxue** [comment]
这是一个Path相关的错误，重启后会自动解决。

libstdc++是MinGW的一个动态链接库，程序在运行时会在Path中查找它。虽然我的工具已经将MinGW添加到Path，但部分应用程序（如资源管理器等）不能及时应用这一改动，于是就会报动态链接失败的错误。重启后该问题就能解决。

如果不希望得到此类错误，可以在配置时勾选“静态链接标准库”选项。

发自我的iPhone
