### ISSUE TITLE
使用3.0.2版本 提示版本过低

### ISSUE THREAD

**Issue by LPShigure** [Guyutongxue/VSCodeConfigHelper3#4]
使用3.0.2版本 提示版本过低，要我使用3.1.0
![QQ截图20210823173553](https://user-images.githubusercontent.com/86432985/130425345-32b6d1cb-ba6d-49ad-a395-41e3c978113f.png)

**Comment by guyutongxue** [comment]
对不起，把开发版本推上去了，马上修复

发自我的iPhone

**Comment by guyutongxue** [comment]
fix in 207164d
